# The Cons of Using AI in the Writing Classroom: Is it Ethical?
There are many ethical concerns when it comes to using AI in academic writing. Some of them include:
- Plagerism: Since some popular AI models, like ChatGPT, don't show where they get their sources from, the fear of accidental plagerism or misuse of information is a common concern for many writers. Additionally, since Gen AI answers are a recomposition of the pieces of writing they were trained off of, it's impossible to know if the writing they produce is plagarism. It is also difficult to tell if the answers provided are factual or not, again due to the lack of sources provided. 
- Discrimination in Training: There are many instances where the materials used in the training of Gen AI models are skewed towards a certain demographic of people, leading the AI model's answers to be racist or sexist in nature. There have also been instances of facial recognition softwares not being able to identify the faces of black women, and in the instances when they did, they often categorized them as black men. 
- Environmental Impacts: Using AI can have many negative environmental effects. The large databases that run these AI models use up tons of energy, pumping a lot of carbon dioxide into the atmosphere. Additionally, submitting a query on a Gen AI model uses up multiple gallons of fresh water, wasting an important natural resource. 
- Critical Thinking and Nuanced Writing: Many people also have concerns about how the use of AI will affect critical thinking skills. In a study by Jialei Jiang and other colleagues, they discovered that some technical writing students were skeptical about using ChatGPT for important parts of the writing process, like thesis writing and the revision stage, for fear of it taking away from their writing voice and critical thinking skills. When describing ChatGPT's writing voices, they claimed it had a "stiffness, technicality, and a lack of naturalness" (Jiang et al.)
##### Connections to Other Posts
1. 2025-09-16-maggie: This post discusses the idea of composing for recomposition. This ties into the idea that AI is changing the meaning of recomposition since all of its work is essentially some form of recomposition.
2. 2025-09-30-hymes: This post discusses the idea that the definition of the term "literacy" is always changing. This is true in terms of AI as some people are beginning to talk about the idea of AI literacy.
3. 2025-09-26-cope: This post discusses how technology has shaped today's society, stating that some people "expect technology to give them answers." This is one of the reasons many people turn to AI in essay writing rather than taking the time to sharpen their critical thinking skills and write the essay themselves.
